### PR TITLE
Create a new farm mission

### PR DESCRIPTION
**Pull request by WalshyDev**
This mission allows players to break crops such as carrots, wheat and coco beans. Usually this wouldn't be possible, so I made a mission!

This will only do ageable crops, so not sugarcane but that can be achieved with block break. 

This has been tested on 1.14.4 and works as intended.

### CODE REVIEW

**Comment by ezeiger92** [comment]
Unfortunately, I added a harvest mission to the [Extras](https://github.com/ezeiger92/QuestWorld-Extensions/tree/master/modules/Extras/src/main/java/com/questworld/extension/extras) extension a long time back that already does this D:
I never thought to check if cocoa beans work with it, but it's something that should be configurable.

**Comment by WalshyDev** [comment]
Personally, I think something so major should really be part of the main plugin. I mean, harvesting is a key part to many many server types. My personal opinion alone of course @ezeiger92

**Comment by ezeiger92** [comment]
I'll consider moving it.

**Comment by ezeiger92** [comment]
For the record, I've moved over the Harvest mission in the 1.15 branch, which will eventually have a build. Maybe in 2021 lol

**Pull request closed without merging**
